### ISSUE TITLE
feature: insert in logs start of uploading the image to registries 

### ISSUE THREAD

**Issue by ksimon1** [codingben/kubevirt-disk-uploader#45]
when the build of image is finished, there is no mention in log, that the uploading started

**Comment by codingben** [comment]
It's mentioned here: https://github.com/codingben/kubevirt-disk-uploader/blob/main/cmd/main.go#L98

**Comment by codingben** [comment]
This issue will be tracked and resolved in [kubevirt/kubevirt-tekton-tasks](https://github.com/kubevirt/kubevirt-tekton-tasks).
