### ISSUE TITLE
Make secret with registry credentials configurable

### ISSUE THREAD

**Issue by ksimon1** [codingben/kubevirt-disk-uploader#58]
In cluster user can have multiple secrets for multiple registries. We should allow user to define which secret the task should use
/cc @codingben

**Comment by codingben** [comment]
@ksimon1 Isn't enough to change the name of the secret [1] and then re-deploy the kubevirt-disk-uploader pod?

[1] https://github.com/codingben/kubevirt-disk-uploader/blob/main/kubevirt-disk-uploader.yaml#L48

**Comment by codingben** [comment]
@ksimon1 Do you mean to multi-registry option? Currently the tool accepts only one registry per execution.

Yes, I think that it would be nice feature to push to multiple registries per execution to populate them with the exported disk image.

**Comment by codingben** [comment]
This issue will be tracked and resolved in [kubevirt/kubevirt-tekton-tasks](https://github.com/kubevirt/kubevirt-tekton-tasks).
